name: release-bake
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: read
  packages: write

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      # checkout for timestamp
      - uses: actions/checkout@v5
      - id: meta
        name: set meta environment variables
        run: |
          echo "EPOCH=1762819200 >> $GITHUB_ENV
          echo "TIMESTAMP=$(git log -1 --pretty=%cI)" >> $GITHUB_OUTPUT
      # set up qemu and buildx
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      # login
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # bake
      - uses: docker/bake-action@v6
        with:
          push: true
        env:
          GITHASH: ${{ steps.meta.outputs.GITHASH }}
          BUILD_DATE: ${{ steps.meta.outputs.TIMESTAMP }}
          SOURCE_DATE_EPOCH: ${{ env.EPOCH }}